--Triggers asociados a las secuencias:
DROP SEQUENCE SEC_idPersona;
DROP SEQUENCE SEC_idUsuario;
DROP SEQUENCE SEC_idDonacion;
DROP SEQUENCE SEC_idCampanya;
DROP SEQUENCE SEC_idMaterial;
DROP SEQUENCE SEC_idCapital;
DROP SEQUENCE SEC_idComentario;
DROP SEQUENCE SEC_idAnonimo;
DROP SEQUENCE SEC_idEmpresa;
DROP SEQUENCE SEC_idAccionHumanitaria;
DROP SEQUENCE SEC_idNoticia;
DROP SEQUENCE SEC_idAsociacionONG;



/*
*
*/
-- SEC_idPersona;
CREATE SEQUENCE SEC_idPersona
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999;
CREATE OR REPLACE TRIGGER TR_SEC_idPersona
BEFORE INSERT ON Persona
FOR EACH ROW 
DECLARE 
valorSec NUMBER:=0;
BEGIN
SELECT SEC_idPersona.NEXTVAL INTO valorSec FROM DUAL;
:NEW.idPersona:=valorSec;
END;
/

-- SEC_idUsuario;
CREATE SEQUENCE SEC_idUsuario
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999;
CREATE OR REPLACE TRIGGER TR_SEC_idUsuario
BEFORE INSERT ON Usuario
FOR EACH ROW 
DECLARE 
valorSec NUMBER:=0;
BEGIN
SELECT SEC_idUsuario.NEXTVAL INTO valorSec FROM DUAL;
:NEW.idUsuario:=valorSec;
END;
/

-- SEC_idDonacion;
CREATE SEQUENCE SEC_idDonacion
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999;
CREATE OR REPLACE TRIGGER TR_SEC_idDonacion
BEFORE INSERT ON Donacion
FOR EACH ROW 
DECLARE 
valorSec NUMBER:=0;
BEGIN
SELECT SEC_idDonacion.NEXTVAL INTO valorSec FROM DUAL;
:NEW.idDonacion:=valorSec;
END;
/

-- SEC_idCampanya;
CREATE SEQUENCE SEC_idCampanya
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999;
CREATE OR REPLACE TRIGGER TR_SEC_idCampanya
BEFORE INSERT ON Campanya
FOR EACH ROW
DECLARE
valorSec NUMBER := 0;
BEGIN
SELECT SEC_idCampanya.NEXTVAL INTO valorSec FROM DUAL;
:NEW.idCampanya := valorSec;
END;
/

-- SEQUENCE SEC_idMaterial;
CREATE SEQUENCE SEC_idMaterial
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999;
CREATE OR REPLACE TRIGGER TR_SEC_idMaterial
BEFORE INSERT ON Material
FOR EACH ROW 
DECLARE 
valorSec NUMBER:=0;
BEGIN
SELECT SEC_idMaterial.NEXTVAL INTO valorSec FROM DUAL;
:NEW.idMaterial:=valorSec;
END;
/

-- SEC_idCapital;
CREATE SEQUENCE SEC_idCapital
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999;
CREATE OR REPLACE TRIGGER TR_SEC_idCapital
BEFORE INSERT ON Capital
FOR EACH ROW 
DECLARE 
valorSec NUMBER:=0;
BEGIN
SELECT SEC_idCapital.NEXTVAL INTO valorSec FROM DUAL;
:NEW.idCapital:=valorSec;
END;
/

-- SEC_idComentario;
CREATE SEQUENCE SEC_idComentario
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999;
CREATE OR REPLACE TRIGGER TR_SEC_idComentario
BEFORE INSERT ON Comentario
FOR EACH ROW 
DECLARE 
valorSec NUMBER:=0;
BEGIN
SELECT SEC_idComentario.NEXTVAL INTO valorSec FROM DUAL;
:NEW.idComentario:=valorSec;
END;
/

-- SEQUENCE SEC_idAnonimo;
CREATE SEQUENCE SEC_idAnonimo
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999;
CREATE OR REPLACE TRIGGER TR_SEC_idAnonimo
BEFORE INSERT ON Anonimo
FOR EACH ROW 
DECLARE 
valorSec NUMBER:=0;
BEGIN
SELECT SEC_idAnonimo.NEXTVAL INTO valorSec FROM DUAL;
:NEW.idAnonimo:=valorSec;
END;
/

-- SEQUENCE SEC_idEmpresa;
CREATE SEQUENCE SEC_idEmpresa
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999;
CREATE OR REPLACE TRIGGER TR_SEC_idEmpresa
BEFORE INSERT ON Institucion
FOR EACH ROW 
DECLARE 
valorSec NUMBER:=0;
BEGIN
SELECT SEC_idEmpresa.NEXTVAL INTO valorSec FROM DUAL;
:NEW.idEmpresa:=valorSec;
END;
/

-- SEQUENCE SEC_idAccionHumanitaria;
CREATE SEQUENCE SEC_idAccionHumanitaria
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999;
CREATE OR REPLACE TRIGGER TR_SEC_idAccionHumanitaria
BEFORE INSERT ON AccionHumanitaria
FOR EACH ROW 
DECLARE 
valorSec NUMBER:=0;
BEGIN
SELECT SEC_idAccionHumanitaria.NEXTVAL INTO valorSec FROM DUAL;
:NEW.idAccionHumanitaria:=valorSec;
END;
/

-- SEQUENCE SEC_idNoticia;
CREATE SEQUENCE SEC_idNoticia
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999;
CREATE OR REPLACE TRIGGER TR_SEC_idNoticia
BEFORE INSERT ON Noticia
FOR EACH ROW 
DECLARE 
valorSec NUMBER:=0;
BEGIN
SELECT SEC_idNoticia.NEXTVAL INTO valorSec FROM DUAL;
:NEW.idNoticia:=valorSec;
END;
/

-- SEQUENCE SEC_idAsociacionONG;
CREATE SEQUENCE SEC_idAsociacionONG
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999;
CREATE OR REPLACE TRIGGER TR_SEC_idAsociacionONG
BEFORE INSERT ON AsociacionONG
FOR EACH ROW 
DECLARE 
valorSec NUMBER:=0;
BEGIN
SELECT SEC_idAsociacionONG.NEXTVAL INTO valorSec FROM DUAL;
:NEW.idAsociacionONG:=valorSec;
END;
/




