---USUARIOS---
SELECT NOMBREUSUARIO,NUMCAMPANYAS,DONACIONANYO,CARGO FROM USUARIO;
--PERSONAS--
SELECT DNI,NOMBRE,APELLIDOS,FECHNACIMIENTO,EMAIL,TELEFONO,DIRECCION FROM PERSONA;
---ACCIONHUMANITARIA-CAMPANYA---
SELECT ACCIONHUMANITARIA.NOMBRE, ACCIONHUMANITARIA.PAIS, ACCIONHUMANITARIA.DESCRIPCION,
CAMPANYA.NOMBRECAMPANYA, CAMPANYA.PRESUPUESTO,CAMPANYA.CAPITALINVERTIDO
FROM ACCIONHUMANITARIA,CAMPANYA WHERE CAMPANYA.IDCAMPANYA = ACCIONHUMANITARIA.IDCAMPANYA;
--PERSONAS QUE HAN DONADO A UNA CAMPAÑA--
SELECT CAMPANYA.NOMBRECAMPANYA,PERSONA.DNI,PERSONA.NOMBRE,PERSONA.APELLIDOS 
FROM PERSONA,CAMPANYA,DONACION
WHERE CAMPANYA.IDDONACION=DONACION.IDDONACION AND DONACION.IDPERSONA=PERSONA.IDPERSONA AND CAMPANYA.NOMBRECAMPANYA='Salvemos Wakanda';
--INFORMACION RELEVANTE DE DIRECTORES VETERANOS--
SELECT PERSONA.DNI,PERSONA.NOMBRE,PERSONA.APELLIDOS,USUARIO.NOMBREUSUARIO,USUARIO.NUMCAMPANYAS,USUARIO.CARGO
FROM PERSONA,USUARIO WHERE PERSONA.IDPERSONA=USUARIO.IDPERSONA AND USUARIO.CARGO='Director Veterano';
--COMENTARIOS DE UNA NOTICIA--
SELECT COMENTARIO.TITULO,COMENTARIO.DESCRIPCION,USUARIO.NOMBREUSUARIO
FROM NOTICIA,COMENTARIO,USUARIO WHERE NOTICIA.IDNOTICIA=COMENTARIO.IDNOTICIA AND COMENTARIO.IDUSUARIO=USUARIO.IDUSUARIO AND NOTICIA.TITULO='Aportacion';
--EMPRESAS QUE HAN DONADO COMIDA--
SELECT MATERIAL.CANTIDAD,INSTITUCION.NOMBREEMPRESA FROM INSTITUCION,MATERIAL,DONACION
WHERE DONACION.IDEMPRESA=INSTITUCION.IDEMPRESA AND MATERIAL.IDMATERIAL=DONACION.IDMATERIAL AND MATERIAL.TIPODEMATERIAL='comida';
--PERSONAS QUE HAN DONADO MAS DE 50 EUROS--
SELECT PERSONA.DNI,PERSONA.NOMBRE,PERSONA.APELLIDOS,USUARIO.NOMBREUSUARIO,CAPITAL.CANTIDAD FROM USUARIO,CAPITAL,DONACION,PERSONA
WHERE PERSONA.IDPERSONA=DONACION.IDPERSONA AND USUARIO.IDPERSONA=PERSONA.IDPERSONA AND CAPITAL.IDCAPITAL=DONACION.IDCAPITAL AND CAPITAL.CANTIDAD>=50;
